test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: lach_dev
  pool: 5
  host: localhost
  username: chiquitienda
  password: lachiquitienda.com

production:
  adapter: postgresql
  encoding: unicode
  database: lach_db
  pool: 5
  host: localhost
  username: chiquitienda
  password: lachiquitienda.com
