test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: lachiqui_dev
  pool: 5
  host: localhost
  username: lachiquitienda
  password: Y7rwlW3a

production:
  adapter: postgresql
  encoding: unicode
  database: lachiqui_db
  pool: 5
  host: localhost
  username: lachiquitienda
  password: Y7rwlW3a
